from typing import Protocol
from uuid import UUID

from src.domain.evidence import EvidencePack
from src.domain.report import Report


class ReportHistory(Protocol):
    def get_by_id(self, report_id: UUID) -> Report | None: ...
    def list_reports(self) -> list[Report]: ...
    def get_by_fingerprint(self, fingerprint: str) -> Report | None: ...
    def save_import_batch(
        self,
        reports: list[Report],
        aliases: dict[UUID, list[str]],
    ) -> None: ...
    def get_evidence(self, report_id: UUID, version: str) -> EvidencePack | None: ...
    def save_evidence(self, evidence: EvidencePack) -> None: ...
